# Generated by Django 5.1.3 on 2024-11-24 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DichVu',
            fields=[
                ('MaDV', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ten', models.CharField(max_length=100)),
                ('giatien', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mota', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LichHen',
            fields=[
                ('MaLH', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('thoigiandangki', models.DateField()),
                ('TrangThai', models.CharField(choices=[('pending', 'Chưa xử lý'), ('processing', 'Đang xử lý'), ('completed', 'Đã hoàn thành'), ('canceled', 'Đã hủy')], default='pending', max_length=20)),
                ('MaDV', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DIVA.dichvu')),
                ('MaKH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='KH_LichHen', to=settings.AUTH_USER_MODEL)),
                ('MaNV', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NV_LichHen', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
