# Generated by Django 4.2.8 on 2024-11-30 03:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DIVA', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KhieuNai_DichVu',
            fields=[
                ('MaKH', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('noidung', models.TextField()),
                ('trangthaixuly', models.CharField(choices=[('Chua', 'Chưa xử lý'), ('Dang', 'Đang xử lý'), ('Da', 'Đã xử lý')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='NguoiDung',
            fields=[
                ('MaUser', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=100)),
                ('VaiTro', models.CharField(choices=[('Nhân viên', 'Nhân viên'), ('Khách hàng', 'Khách hàng')], default='Khách hàng', max_length=20)),
                ('Username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='lichhen',
            options={'ordering': ['thoigiandangki']},
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('MaUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='DIVA.nguoidung')),
                ('hoten', models.CharField(max_length=50)),
                ('ngaysinh', models.DateField()),
                ('sodienthoai', models.IntegerField()),
                ('diachi', models.CharField(max_length=120)),
                ('is_Enable', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='YeuCauTuVan',
            fields=[
                ('MaYCTV', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('TenKH', models.CharField(max_length=100)),
                ('SDT', models.CharField(max_length=10)),
                ('TrangThai', models.CharField(choices=[('Chưa xử lý', 'Chưa xử lý'), ('Đang xử lý', 'Đang xử lý'), ('Tư vấn lại', 'Tư vấn lại')], default='Chưa xử lý', max_length=20)),
                ('MaDV', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DIVA.dichvu')),
                ('MaNV', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NV_YCTV', to='DIVA.nguoidung')),
            ],
        ),
        migrations.CreateModel(
            name='YeuCau_DichVu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MaDV', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DIVA.dichvu')),
                ('MaYCTV', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DIVA.yeucautuvan')),
            ],
        ),
        migrations.CreateModel(
            name='LichHen_DichVu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MaDV', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DIVA.dichvu')),
                ('MaLH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DIVA.lichhen')),
            ],
        ),
        migrations.CreateModel(
            name='KhieuNai_LichHen',
            fields=[
                ('MaKN', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('NoiDung', models.TextField()),
                ('TrangThai', models.CharField(choices=[('Chưa xử lý', 'Chưa xử lý'), ('Đang xử lý', 'Đang xử lý'), ('Đã hoàn thành', 'Đã hoàn thành')], default='Chưa xử lý', max_length=20)),
                ('MaKH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='KH_KNLH', to='DIVA.nguoidung')),
                ('MaLH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DIVA.lichhen')),
                ('MaNV', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NV_KNLH', to='DIVA.nguoidung')),
            ],
        ),
        migrations.CreateModel(
            name='DichVuDaDung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MaDV', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DIVA.dichvu')),
                ('MaKN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DIVA.khieunai_dichvu')),
                ('MaUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DIVA.nguoidung')),
            ],
        ),
    ]
