# Generated by Django 4.2.8 on 2024-11-30 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DIVA', '0002_khieunai_dichvu_nguoidung_alter_lichhen_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yeucautuvan',
            name='MaNV',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='NV_YCTV', to=settings.AUTH_USER_MODEL),
        ),
    ]
