# Generated by Django 4.2.8 on 2024-12-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DIVA', '0004_profile_vaitro_alter_dichvudadung_mauser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yeucautuvan',
            name='GhiChu',
            field=models.TextField(blank=True, null=True),
        ),
    ]
