# Generated by Django 4.2.8 on 2024-12-09 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DIVA', '0006_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['timestamp']},
        ),
    ]
