# Generated by Django 4.2.8 on 2024-12-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DIVA', '0008_message_anonymous_sender_alter_message_receiver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.AddField(
            model_name='message',
            name='is_from_admin',
            field=models.BooleanField(default=False),
        ),
    ]
