# Generated by Django 4.2.8 on 2024-12-10 08:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DIVA', '0012_alter_message_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Conversation',
            new_name='HoiThoai',
        ),
        migrations.RenameModel(
            old_name='Message',
            new_name='TinNhan',
        ),
    ]
