# Generated by Django 4.2.8 on 2024-12-11 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DIVA', '0013_rename_conversation_hoithoai_rename_message_tinnhan'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaiViet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nguoi_tao', models.CharField(max_length=500)),
                ('tieu_de', models.CharField(max_length=500)),
                ('hinh_anh', models.ImageField(upload_to='')),
                ('noi_dung', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('ngay_tao', models.DateField(auto_now_add=True)),
                ('thoi_gian_dang', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
