# Generated by Django 4.2.8 on 2024-12-11 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DIVA', '0014_baiviet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_Enable',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_locked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='lock_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lichhen',
            name='MaNV',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='NV_LichHen', to=settings.AUTH_USER_MODEL),
        ),
    ]
