# Generated by Django 4.2.8 on 2024-12-11 03:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DIVA', '0015_remove_profile_is_enable_profile_is_locked_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiemTichLuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DiemTichLuy', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('NgayTichDiem', models.DateField(default=django.utils.timezone.now)),
                ('MaUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diem_tich_luy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KhieuNai',
            fields=[
                ('MaKN', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('LoaiKhieuNai', models.CharField(choices=[('Dịch Vụ', 'Dịch vụ'), ('Lịch Hẹn', 'Lịch hẹn')], default='DichVu', max_length=10)),
                ('NoiDung', models.TextField()),
                ('NgayXayRa', models.DateField()),
                ('TrangThai', models.CharField(choices=[('Chưa xử lý', 'Chưa xử lý'), ('Đang xử lý', 'Đang xử lý'), ('Đã hoàn thành', 'Đã hoàn thành')], default='Chưa xử lý', max_length=20)),
                ('NgayTiepNhan', models.DateField(auto_now_add=True, null=True)),
                ('NguoiPhuTrach', models.CharField(blank=True, max_length=100, null=True)),
                ('MaKH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='KH_KN', to=settings.AUTH_USER_MODEL)),
                ('MaNV', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='NV_KN', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='KhieuNai_LichHen',
        ),
        migrations.AlterField(
            model_name='dichvudadung',
            name='MaKN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DIVA.khieunai'),
        ),
        migrations.DeleteModel(
            name='KhieuNai_DichVu',
        ),
    ]
